### PR TITLE
Added on-device-only setup

### PR DESCRIPTION
**Pull request by mh-**
(This is not a full pull request yet, just have an initial look, please ;)

By using git-inject with --parameters, this can be used on the device itself, without the need to attach a computer and run scripts on that computer.
I did however not yet find a consistent way to run it automatically at boot.

### CODE REVIEW

**Comment by kbobrowski** [comment]
Thanks, this would be very useful :) I will look into it, perhaps for running at boot it can be wrapped in magisk module, similar to https://github.com/ViRb3/magisk-frida

**Comment by kbobrowski** [comment]
`inject.sh` will run with resistance to crashing frida server / GMS

**Comment by kbobrowski** [comment]
added simple Magisk module which just executes `inject.sh` from `/data/local/tmp` on boot, seems to be working robustly

**Comment by mh-** [comment]
Looks good to me :)
Successfully tested on Android 9.

Since everything is now already included in the master branch, I will close this PR.

I think a next step could be to optionally disable external frida access, to prevent misuse.

**Pull request closed without merging**
